# To use:
#
#     pre-commit run -a
#
# Or:
#
#     pre-commit install  # (runs every time you commit in git)
#
# To update this file:
#
#     pre-commit autoupdate
#
# See https://pre-commit.com for more information

# Do not check/format anything from third parties
#exclude: '^thirdParty/abc'

# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
    - id: end-of-file-fixer
      exclude: '.json$'
    - id: mixed-line-ending
    - id: check-json
    - id: check-toml
    - id: check-yaml
    - id: check-added-large-files
    - id: requirements-txt-fixer
#  - id: fix-encoding-pragma
#    exclude: ^noxfile.py$

#- repo: https://github.com/asottile/pyupgrade
#  rev: v2.29.0
#  hooks:
#  - id: pyupgrade

# Changes tabs to spaces
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.5.5
  hooks:
  - id: remove-tabs
#    exclude: 'makefile|Makefile|GNUmake'

# Python Formatting
#- repo: https://github.com/psf/black
#  rev: 21.10b0 # Keep in sync with blacken-docs
#  hooks:
#  - id: black
#- repo: https://github.com/asottile/blacken-docs
#  rev: v1.11.0
#  hooks:
#  - id: blacken-docs
#    additional_dependencies:
#    - black==21.10b0 # keep in sync with black hook
